<?php
class OperationsMethodMap {
  public static function getMethodsMap() {
    return array(
      'saveManifest' => dirname(__FILE__) . '/saveManifest.php',
      'saveSeoSettings' => dirname(__FILE__) . '/saveSeoSettings.php',
      'saveAppearanceSettings' => dirname(__FILE__) . '/saveAppearanceSettings.php',
      'savePlatformSettings' => dirname(__FILE__) . '/savePlatformSettings.php',
      'saveEditorSettings' => dirname(__FILE__) . '/saveEditorSettings.php',
      'saveAllowedBlocks' => dirname(__FILE__) . '/saveAllowedBlocks.php',
      'saveEnabledBlocks' => dirname(__FILE__) . '/saveEnabledBlocks.php',
      'saveOutline' => dirname(__FILE__) . '/saveOutline.php',
      'createNode' => dirname(__FILE__) . '/createNode.php',
      'saveNode' => dirname(__FILE__) . '/saveNode.php',
      'deleteNode' => dirname(__FILE__) . '/deleteNode.php',
      'saveNodeDetails' => dirname(__FILE__) . '/saveNodeDetails.php',
      'getNodeRevisions' => dirname(__FILE__) . '/nodeRevisions.php',
      'getNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'restoreNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'connectionSettings' => dirname(__FILE__) . '/connectionSettings.php',
      'appStoreSearch' => dirname(__FILE__) . '/appStoreSearch.php',
      'generateAppStore' => dirname(__FILE__) . '/generateAppStore.php',
      'systemBlocksList' => dirname(__FILE__) . '/systemBlocksList.php',
      'getUserData' => dirname(__FILE__) . '/getUserData.php',
      'fileOperation' => dirname(__FILE__) . '/fileOperation.php',
      'siteSearch' => dirname(__FILE__) . '/siteSearch.php',
      'login' => dirname(__FILE__) . '/login.php',
      'logout' => dirname(__FILE__) . '/logout.php',
      'refreshAccessToken' => dirname(__FILE__) . '/refreshAccessToken.php',
      'systemStatus' => dirname(__FILE__) . '/systemStatus.php',
      'schemaFileOperation' => dirname(__FILE__) . '/schemaFileOperation.php',
      'saveFile' => dirname(__FILE__) . '/saveFile.php',
      'skeletonsList' => dirname(__FILE__) . '/skeletonsList.php',
      'themesList' => dirname(__FILE__) . '/themesList.php',
      'getSkeleton' => dirname(__FILE__) . '/getSkeleton.php',
      'listSites' => dirname(__FILE__) . '/listSites.php',
      'createSite' => dirname(__FILE__) . '/createSite.php',
      'cloneSite' => dirname(__FILE__) . '/cloneSite.php',
      'downloadSite' => dirname(__FILE__) . '/downloadSite.php',
      'downloadSiteSkeleton' => dirname(__FILE__) . '/downloadSiteSkeleton.php',
      'saveSiteAsTemplate' => dirname(__FILE__) . '/saveSiteAsTemplate.php',
      'archiveSite' => dirname(__FILE__) . '/archiveSite.php',
      'haxiamAddUserAccess' => dirname(__FILE__) . '/haxiamAddUserAccess.php',
    );
  }
}
