<?php
include_once dirname(__FILE__) . '/../SiteRouteUtils.php';
return function ($context) {
    $site = isset($context->site) ? $context->site : null;
    $apiBasePath = isset($context->apiBasePath) ? $context->apiBasePath : '/x/api';
    if (!isset($site) || !isset($site->manifest)) {
        SiteRouteUtils::sendFormattedResponse(
            array('message' => 'Unable to resolve site context for /x/api/v1/entities'),
            array('statusCode' => 404, 'allowedFormats' => array('json'), 'defaultFormat' => 'json'),
            $context->routeSuffix,
            $apiBasePath
        );
        return;
    }
    $entities = array(
        array(
            'name' => 'site',
            'description' => 'Site-level metadata and API capability summary.',
            'primaryKey' => 'id',
            'endpoints' => array(
                $apiBasePath . '/v1/site',
                $apiBasePath . '/v1/site/export/{format}',
            ),
            'filterableFields' => array(),
            'sortableFields' => array('title', 'updated'),
            'selectableFields' => array(
                'id',
                'name',
                'title',
                'description',
                'language',
                'basePath',
                'theme',
                'updated',
                'counts',
                'links',
                'jsonld',
            ),
            'includes' => array(),
            'formats' => array('application/json'),
            'modes' => array(),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'item',
            'description' => 'Outline item metadata records and hierarchy.',
            'primaryKey' => 'id',
            'endpoints' => array(
                $apiBasePath . '/v1/items',
                $apiBasePath . '/v1/items/{idOrSlug}',
                $apiBasePath . '/v1/items/{idOrSlug}/export/{format}',
            ),
            'filterableFields' => array(
                'filter.parent',
                'filter.ancestor',
                'filter.depth',
                'filter.tags',
                'filter.pageType',
                'filter.published',
                'filter.region',
            ),
            'sortableFields' => array('title', 'order', 'updated', 'created'),
            'selectableFields' => array(
                'id',
                'title',
                'slug',
                'parent',
                'indent',
                'order',
                'description',
                'metadata',
                'links',
                'exports',
                'jsonld',
                'haxElementSchema',
            ),
            'includes' => array('content', 'tags', 'region', 'jsonld', 'haxElementSchema'),
            'formats' => array(
                'application/json',
                'text/markdown',
                'application/yaml',
                'application/xml',
                'text/html',
            ),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
            'related' => array(
                array(
                    'rel' => 'entity',
                    'type' => 'item',
                    'href' => $apiBasePath . '/v1/entities#item',
                ),
                array(
                    'rel' => 'schema',
                    'type' => 'jsonOutlineSchema',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=jsonOutlineSchema',
                ),
                array(
                    'rel' => 'schema',
                    'type' => 'jsonOutlineSchemaItem',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=jsonOutlineSchemaItem',
                ),
            ),
        ),
        array(
            'name' => 'content',
            'description' => 'Page body/content representations and transformed variants.',
            'primaryKey' => 'id',
            'endpoints' => array(
                $apiBasePath . '/v1/content',
                $apiBasePath . '/v1/content/{idOrSlug}',
            ),
            'filterableFields' => array(
                'filter.parent',
                'filter.ancestor',
                'filter.depth',
                'filter.tags',
                'filter.published',
                'filter.region',
            ),
            'sortableFields' => array('title', 'updated', 'created'),
            'selectableFields' => array('id', 'slug', 'title', 'format', 'mode', 'body'),
            'includes' => array('item', 'region', 'tags'),
            'formats' => array(
                'application/json',
                'text/markdown',
                'application/yaml',
                'application/xml',
                'text/html',
            ),
            'modes' => array('bundle', 'concat'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'file',
            'description' => 'File assets available in the site files directory.',
            'primaryKey' => 'path',
            'endpoints' => array($apiBasePath . '/v1/files'),
            'filterableFields' => array('filter.type', 'filter.extension', 'filter.startsWith', 'filter.nameContains'),
            'sortableFields' => array('name', 'path', 'dateCreated', 'size'),
            'selectableFields' => array('path', 'url', 'fullUrl', 'name', 'mimetype', 'size', 'dateCreated'),
            'includes' => array(),
            'formats' => array(
                'application/json',
                'text/markdown',
                'application/yaml',
                'application/xml',
            ),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'tag',
            'description' => 'Tag facet values and usage counts.',
            'primaryKey' => 'tag',
            'endpoints' => array($apiBasePath . '/v1/tags'),
            'filterableFields' => array('filter.tags'),
            'sortableFields' => array('tag', 'count'),
            'selectableFields' => array('tag', 'count'),
            'includes' => array('items'),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'customElement',
            'description' => 'Custom element metadata available to the site.',
            'primaryKey' => 'tag',
            'endpoints' => array(
                $apiBasePath . '/v1/custom-elements',
                $apiBasePath . '/v1/custom-elements/{webcomponentName}',
            ),
            'filterableFields' => array('filter.tag'),
            'sortableFields' => array('tag'),
            'selectableFields' => array('tag', 'import', 'package', 'description', 'haxProperties'),
            'includes' => array('haxProperties', 'haxSchema', 'haxElementSchema'),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
            'related' => array(
                array(
                    'rel' => 'entity',
                    'type' => 'block',
                    'href' => $apiBasePath . '/v1/entities#block',
                ),
                array(
                    'rel' => 'endpoint',
                    'type' => 'usage',
                    'href' => $apiBasePath . '/v1/blocks/{webcomponentName}/usage',
                ),
                array(
                    'rel' => 'schema',
                    'type' => 'haxProperties',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=haxProperties',
                ),
                array(
                    'rel' => 'schema',
                    'type' => 'haxSchema',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=haxSchema',
                ),
                array(
                    'rel' => 'schema',
                    'type' => 'haxElementSchema',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=haxElementSchema',
                ),
            ),
        ),
        array(
            'name' => 'block',
            'description' => 'Block usage and HAX schema details for custom element tags.',
            'primaryKey' => 'tag',
            'endpoints' => array(
                $apiBasePath . '/v1/blocks',
                $apiBasePath . '/v1/blocks/{webcomponentName}',
                $apiBasePath . '/v1/blocks/{webcomponentName}/usage',
            ),
            'filterableFields' => array('filter.tag', 'filter.enabled', 'filter.region'),
            'sortableFields' => array('tag', 'usageCount'),
            'selectableFields' => array('tag', 'enabled', 'usageCount', 'haxProperties', 'haxSchema', 'haxElementSchema'),
            'includes' => array('item', 'region', 'haxProperties', 'haxSchema', 'haxElementSchema'),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'region',
            'description' => 'Region-level grouping of site items and content.',
            'primaryKey' => 'name',
            'endpoints' => array(
                $apiBasePath . '/v1/regions',
                $apiBasePath . '/v1/regions/{regionName}',
            ),
            'filterableFields' => array('filter.region'),
            'sortableFields' => array('name', 'count'),
            'selectableFields' => array('name', 'count'),
            'includes' => array('items'),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'theme',
            'description' => 'Theme metadata records, including active and available themes.',
            'primaryKey' => 'machineName',
            'endpoints' => array(
                $apiBasePath . '/v1/themes',
                $apiBasePath . '/v1/themes/{themeName}',
                $apiBasePath . '/v1/themes/active',
            ),
            'filterableFields' => array('filter.enabled', 'filter.active'),
            'sortableFields' => array('machineName', 'name'),
            'selectableFields' => array('machineName', 'name', 'description', 'enabled', 'active', 'screenshot'),
            'includes' => array(),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'report',
            'description' => 'Report datasets used by dashboards.',
            'primaryKey' => 'id',
            'endpoints' => array(
                $apiBasePath . '/v1/reports',
                $apiBasePath . '/v1/reports/{report}',
            ),
            'filterableFields' => array('filter.report', 'filter.parent', 'filter.ancestor'),
            'sortableFields' => array('id', 'generatedAt'),
            'selectableFields' => array('id', 'title', 'description', 'generatedAt', 'data'),
            'includes' => array('items', 'links', 'content', 'media'),
            'formats' => array(
                'application/json',
                'text/markdown',
                'application/yaml',
                'application/xml',
            ),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'analytics',
            'description' => 'Analytics capabilities and future xAPI-oriented reporting surface.',
            'primaryKey' => 'id',
            'endpoints' => array($apiBasePath . '/v1/analytics'),
            'filterableFields' => array(),
            'sortableFields' => array(),
            'selectableFields' => array('mode', 'xapi', 'notes'),
            'includes' => array(),
            'formats' => array('application/json'),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
            'related' => array(
                array(
                    'rel' => 'schema',
                    'type' => 'xapi',
                    'href' => $apiBasePath . '/v1/schemas?filter.kind=xapi',
                ),
            ),
        ),
        array(
            'name' => 'view',
            'description' => 'Saved display/view definitions and resolved results.',
            'primaryKey' => 'id',
            'endpoints' => array(
                $apiBasePath . '/v1/views',
                $apiBasePath . '/v1/views/{viewId}',
                $apiBasePath . '/v1/views/{viewId}/results',
                $apiBasePath . '/v1/displays',
                $apiBasePath . '/v1/displays/{viewId}/results',
            ),
            'filterableFields' => array('filter.view', 'filter.tags', 'filter.region'),
            'sortableFields' => array('id', 'title'),
            'selectableFields' => array('id', 'title', 'description', 'query', 'display'),
            'includes' => array('results'),
            'formats' => array(
                'application/json',
                'text/markdown',
                'application/yaml',
                'application/xml',
            ),
            'modes' => array('bundle'),
            'auth' => 'public',
            'supportedOperations' => array('read'),
        ),
        array(
            'name' => 'user',
            'description' => 'User identity and operations are reserved for secured APIs and future phases.',
            'primaryKey' => 'id',
            'endpoints' => array(),
            'filterableFields' => array(),
            'sortableFields' => array(),
            'selectableFields' => array('id', 'name', 'roles', 'permissions'),
            'includes' => array(),
            'formats' => array('application/json'),
            'modes' => array(),
            'auth' => 'authenticated',
            'supportedOperations' => array(),
            'enabled' => false,
            'notes' => array('Reserved for future secured routes; not exposed on public site API in read-only phase.'),
        ),
    );
    SiteRouteUtils::sendFormattedResponse(
        array(
            'count' => count($entities),
            'entities' => $entities,
            'links' => array(
                'self' => $apiBasePath . '/v1/entities',
                'site' => $apiBasePath . '/v1/site',
                'schemas' => $apiBasePath . '/v1/schemas',
                'openapi' => $apiBasePath . '/openapi',
                'openapiJson' => $apiBasePath . '/openapi.json',
                'openapiYaml' => $apiBasePath . '/openapi.yaml',
            ),
        ),
        array('allowedFormats' => array('json'), 'defaultFormat' => 'json'),
        $context->routeSuffix,
        $apiBasePath
    );
};