<?php
class OperationsRoutesMap {
  public static function getRoutesMap() {
    return array(
      'options' => dirname(__FILE__) . '/options.php',
      'api' => dirname(__FILE__) . '/api.php',
      'openapi' => dirname(__FILE__) . '/openapi.php',
      'saveManifest' => dirname(__FILE__) . '/saveManifest.php',
      'saveSeoSettings' => dirname(__FILE__) . '/saveSeoSettings.php',
      'saveAppearanceSettings' => dirname(__FILE__) . '/saveAppearanceSettings.php',
      'savePlatformSettings' => dirname(__FILE__) . '/savePlatformSettings.php',
      'saveEditorSettings' => dirname(__FILE__) . '/saveEditorSettings.php',
      'saveAllowedBlocks' => dirname(__FILE__) . '/saveAllowedBlocks.php',
      'saveEnabledBlocks' => dirname(__FILE__) . '/saveEnabledBlocks.php',
      'saveOutline' => dirname(__FILE__) . '/saveOutline.php',
      'createNode' => dirname(__FILE__) . '/createNode.php',
      'saveNode' => dirname(__FILE__) . '/saveNode.php',
      'deleteNode' => dirname(__FILE__) . '/deleteNode.php',
      'saveNodeDetails' => dirname(__FILE__) . '/saveNodeDetails.php',
      'getNodeRevisions' => dirname(__FILE__) . '/nodeRevisions.php',
      'getNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'restoreNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'siteUpdateAlternateFormats' => dirname(__FILE__) . '/siteUpdateAlternateFormats.php',
      'connectionSettings' => dirname(__FILE__) . '/connectionSettings.php',
      'connectionTest' => dirname(__FILE__) . '/connectionTest.php',
      'generateAppStore' => dirname(__FILE__) . '/generateAppStore.php',
      'systemBlocksList' => dirname(__FILE__) . '/systemBlocksList.php',
      'getUserData' => dirname(__FILE__) . '/getUserData.php',
      'formLoad' => dirname(__FILE__) . '/formLoad.php',
      'formProcess' => dirname(__FILE__) . '/formProcess.php',
      'listFiles' => dirname(__FILE__) . '/listFiles.php',
      'fileOperation' => dirname(__FILE__) . '/fileOperation.php',
      'siteSearch' => dirname(__FILE__) . '/siteSearch.php',
      'insights' => dirname(__FILE__) . '/insights.php',
      'linkChecker' => dirname(__FILE__) . '/linkChecker.php',
      'contentBrowser' => dirname(__FILE__) . '/contentBrowser.php',
      'mediaBrowser' => dirname(__FILE__) . '/mediaBrowser.php',
      'login' => dirname(__FILE__) . '/login.php',
      'logout' => dirname(__FILE__) . '/logout.php',
      'refreshAccessToken' => dirname(__FILE__) . '/refreshAccessToken.php',
      'systemStatus' => dirname(__FILE__) . '/systemStatus.php',
      'getApiKeys' => dirname(__FILE__) . '/getApiKeys.php',
      'saveApiKeys' => dirname(__FILE__) . '/saveApiKeys.php',
      'getMediaSettings' => dirname(__FILE__) . '/getMediaSettings.php',
      'saveMediaSettings' => dirname(__FILE__) . '/saveMediaSettings.php',
      'saveEnabledSkeletons' => dirname(__FILE__) . '/saveEnabledSkeletons.php',
      'schemaFileOperation' => dirname(__FILE__) . '/schemaFileOperation.php',
      'saveEnabledThemes' => dirname(__FILE__) . '/saveEnabledThemes.php',
      'saveFile' => dirname(__FILE__) . '/saveFile.php',
      'skeletonsList' => dirname(__FILE__) . '/skeletonsList.php',
      'themesList' => dirname(__FILE__) . '/themesList.php',
      'getSkeleton' => dirname(__FILE__) . '/getSkeleton.php',
      'listSites' => dirname(__FILE__) . '/listSites.php',
      'createSite' => dirname(__FILE__) . '/createSite.php',
      'cloneSite' => dirname(__FILE__) . '/cloneSite.php',
      'downloadSite' => dirname(__FILE__) . '/downloadSite.php',
      'downloadSiteSkeleton' => dirname(__FILE__) . '/downloadSiteSkeleton.php',
      'saveSiteAsTemplate' => dirname(__FILE__) . '/saveSiteAsTemplate.php',
      'archiveSite' => dirname(__FILE__) . '/archiveSite.php',
      'haxiamAddUserAccess' => dirname(__FILE__) . '/haxiamAddUserAccess.php',
      'openapi/json' => dirname(__FILE__) . '/openapi.php',
    );
  }
  public static function getSystemAdminRoutes() {
    return array(
      'systemStatus',
      'getApiKeys',
      'saveApiKeys',
      'getMediaSettings',
      'saveMediaSettings',
      'saveEnabledSkeletons',
      'schemaFileOperation',
      'saveEnabledThemes',
      'saveEnabledBlocks',
      'systemBlocksList',
    );
  }
  public static function isSystemAdminRoute($routeName) {
    return in_array($routeName, self::getSystemAdminRoutes(), true);
  }
}
