<?php
class OperationsRoutesMap {
  public static function getRoutesMap() {
    return array(
      'options' => dirname(__FILE__) . '/options.php',
      'api' => dirname(__FILE__) . '/api.php',
      'openapi' => dirname(__FILE__) . '/openapi.php',
      'saveManifest' => dirname(__FILE__) . '/saveManifest.php',
      'saveSeoSettings' => dirname(__FILE__) . '/saveSeoSettings.php',
      'saveAppearanceSettings' => dirname(__FILE__) . '/saveAppearanceSettings.php',
      'savePlatformSettings' => dirname(__FILE__) . '/savePlatformSettings.php',
      'saveEditorSettings' => dirname(__FILE__) . '/saveEditorSettings.php',
      'saveAllowedBlocks' => dirname(__FILE__) . '/saveAllowedBlocks.php',
      'saveOutline' => dirname(__FILE__) . '/saveOutline.php',
      'createNode' => dirname(__FILE__) . '/createNode.php',
      'saveNode' => dirname(__FILE__) . '/saveNode.php',
      'deleteNode' => dirname(__FILE__) . '/deleteNode.php',
      'saveNodeDetails' => dirname(__FILE__) . '/saveNodeDetails.php',
      'getNodeRevisions' => dirname(__FILE__) . '/nodeRevisions.php',
      'getNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'restoreNodeRevision' => dirname(__FILE__) . '/nodeRevisions.php',
      'siteUpdateAlternateFormats' => dirname(__FILE__) . '/siteUpdateAlternateFormats.php',
      'connectionSettings' => dirname(__FILE__) . '/connectionSettings.php',
      'generateAppStore' => dirname(__FILE__) . '/generateAppStore.php',
      'getUserData' => dirname(__FILE__) . '/getUserData.php',
      'formLoad' => dirname(__FILE__) . '/formLoad.php',
      'formProcess' => dirname(__FILE__) . '/formProcess.php',
      'listFiles' => dirname(__FILE__) . '/listFiles.php',
      'fileOperation' => dirname(__FILE__) . '/fileOperation.php',
      'siteSearch' => dirname(__FILE__) . '/siteSearch.php',
      'login' => dirname(__FILE__) . '/login.php',
      'logout' => dirname(__FILE__) . '/logout.php',
      'refreshAccessToken' => dirname(__FILE__) . '/refreshAccessToken.php',
      'saveFile' => dirname(__FILE__) . '/saveFile.php',
      'skeletonsList' => dirname(__FILE__) . '/skeletonsList.php',
      'getSkeleton' => dirname(__FILE__) . '/getSkeleton.php',
      'listSites' => dirname(__FILE__) . '/listSites.php',
      'createSite' => dirname(__FILE__) . '/createSite.php',
      'cloneSite' => dirname(__FILE__) . '/cloneSite.php',
      'downloadSite' => dirname(__FILE__) . '/downloadSite.php',
      'downloadSiteSkeleton' => dirname(__FILE__) . '/downloadSiteSkeleton.php',
      'saveSiteAsTemplate' => dirname(__FILE__) . '/saveSiteAsTemplate.php',
      'archiveSite' => dirname(__FILE__) . '/archiveSite.php',
      'haxiamAddUserAccess' => dirname(__FILE__) . '/haxiamAddUserAccess.php',
      'openapi/json' => dirname(__FILE__) . '/openapi.php',
    );
  }
}
